
services:

  # 2. Cấu hình .NET Web App
  # 2. Cấu hình .NET Web App
  web:
    build:
      context: ./Web 
      dockerfile: Dockerfile
    ports:
      # SỬA 80 THÀNH 8080 Ở ĐÂY:
      - "8080:8080" 
    environment:
      - ConnectionStrings__PBL3ConnectionString=Server=tcp:studyshare-db-tin.database.windows.net,1433;Initial Catalog=StudyShareDB;Persist Security Info=False;User ID=hoangtin;Password=Tin@1234;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
      - AIServiceUrl=http://aiservice:8000/
      - MailSettings__Mail=hoangtin422006@gmail.com
      - MailSettings__DisplayName=StudyShare
      - MailSettings__Password=gnmvcdhnwgljyyel
      - MailSettings__Host=smtp.gmail.com
      - MailSettings__Port=587
    volumes:
      - dataprotection_keys:/app/dataprotection-keys
      - web_uploads:/app/wwwroot/uploads
  # 3. Cấu hình AI Service (Python)
  aiservice:
    build:
      context: ./Ai
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./Ai/.env

volumes:
  dataprotection_keys:
  web_uploads: